#!/bin/bash -e
./gradlew clean test publish bintrayUpload

version=$(cat manifest.gradle | grep "library_version" | tr "'" '\n' | head -n 2 | tail -n 1)
./generate-debug-apk
hub release create -a uploadservice-demo-debug.apk -m "$version" "$version"
